[global]
require-virtualenv = true
disable-pip-version-check = true
timeout = 30
pre = false
uploaded-prior-to = P2D
no-cache-dir = true
prefer-binary = true

[install]
upgrade = true
upgrade-strategy = eager
no-compile = true

[list]
format = freeze
